"""empty message

Revision ID: 462cc99ad18b
Revises: 595d4bb11f48
Create Date: 2025-05-23 20:20:57.803470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462cc99ad18b'
down_revision = '595d4bb11f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('current_area', sa.Integer(), nullable=True),
    sa.Column('attemps', sa.Integer(), nullable=True),
    sa.Column('defeat', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enemy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('current_area', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attack', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_area', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('money', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('xp', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('xp')
        batch_op.drop_column('money')
        batch_op.drop_column('current_area')
        batch_op.drop_column('attack')
        batch_op.drop_column('hp')

    op.drop_table('enemy')
    op.drop_table('boss')
    # ### end Alembic commands ###
